File path display
pwsafe/pwsafe pull request #1335
Opened 2024-07-09 18:58 UTC by rafaelx

Resolves #1331.
Resolves #1332.

2024-07-10 01:01 UTC, nobugshere requested changes
@rafaelx ,
Your last commit is causing a serious regression (at least on the Mac, I haven't tried Linux yet.)  Since you no longer save and restore m_filename, it's getting set to the "elipsised" version.  Among the problems this causes: I can't open a file unless I make the window wide enough for the name without ellipses.  Could this be because of the SetValidator @SafeCombinationEntryDlg:233 ?

Also, whatever you wind-up doing in OnOk() will most likely be needed in OnYubibtnClick() as well.

2024-07-10 12:21 UTC, rafaelx commented
For me it works without any problems under Kubuntu. When you move the mouse over the combobox, does the tooltip show the full path or the shortened path? (The tooltip is always updated based on m_filename.)

I have placed a trace function in each event handler and in the function SafeCombinationEntryDlg::EllipsizeFilePathname to be able to observe the member m_filename and the contents of the combobox. m_filename always points to the full path. Only the combobox shows the shortened path. In OnOk the combobox is set to the full path before further activities are executed.

2024-07-10 19:38 UTC, nobugshere commented
There's definitely some magic that happens in WX that I don't fully understand yet.  But, I what I think is happening is that the calls to ChangeValue() are generating wxEVT_TEXT events, even though the WX documentation says it doesn't!  This leads to the GetValue() call at line 272 (the wxEVT_TEXT event handler) after the shortened name has been set.

Focusing on SafeCombinationEntryDlg.cpp, here are some of the observations that lead me to that conclusion:
1. I can't reproduce the problem on a Fedora/Xfce VM, only the native Mac build.
2. On initial launch, if the file I want is selected by default, I can open it regardless of how it's displayed in the combobox.
3. On initial launch, if I simply click the text part of the filename box, then click back to the password box, I cannot open the file if the name was shortened.  (File not found.)
4. If I make the window wide enough that ellipses are not needed, I can always open the file.
5. I discovered that the combobox tooltip never did work on macOS.  Apparently, wxEVT_MOTION is not being delivered, so the tooltip is not being set at line ~240.
6. If I place the call to SetTooltip() at the end of EllipsizeFilePathname(), the tooltip works, **_but displays the ellipsized name_**.
7. Setting breakpoints, m_filename is correct on entry to EllipsizeFilePathname() and on call to Ellipsize().  
8. After return from ChangeValue(), before anything else, m_filename has been changed to the shortened version.  This happens even if I comment-out the validator at line 233.
9. I breakpointed the event handlers and clicked back and forth between boxes, I noticed the wxEVT_TEXT events each time ChangeValue() is called.
10. Finally, I can comment-out the wxEVT_TEXT event handler and things work better.

Do your traces show any evidence of wxEVT_TEXT following a call to ChangeValue()?  I assume not.

Conclusions:
1. Possible macOS specific bug in wxWidgets causing wxEVT_TEXT events after a call to ChangeValue(), contrary to the documentation.
2. Since wxEVT_TEXT doesn't work right and wxEVT_MOTION doesn't work at all, we can't rely on those events to manage the tooltip or m_filename.  
3. I think by setting the tooltip in EllipsizeFilePathname(), we can eliminate those two event handlers and rework the others so that GetValue() is never called after EllipsizeFilePathname().  However, I haven't actually thought through the various set_focus, kill_focus, combobox, scenarios yet.

2024-07-10 22:16 UTC, rafaelx commented
I don't see a wxEVT_TEXT event in my trace after ChangeValue was called. The event only occurs when the text in the combobox is edited. So I see a behavior that conforms to the documentation. It does indeed look like a bug in WX.

If it is helpful for further investigation, here is the trace function I used, which I placed in the header file.
```
void Trace(const wxString& name) {
  pws_os::Trace(L"[TRACE] Function: '%ls' / m_filename: '%ls' / Combobox: '%ls'", name.wc_str(), m_filename.wc_str(), (m_filenameCB->GetValue()).wc_str());
}
```

Similar to the previous version, the full path could be stored in a temporary variable to restore the path in m_filename after calling ChangeValue.
```
void SafeCombinationEntryDlg::EllipsizeFilePathname()
{
  if (m_filename.IsEmpty()) {
    return;
  }

  wxScreenDC dc;
#ifdef __WXOSX__
  wxString filename(m_filename);
#endif
  m_filenameCB->ChangeValue(
    wxControl::Ellipsize(
      m_filename, dc, wxEllipsizeMode::wxELLIPSIZE_MIDDLE,
      /* The limiting width for the text is the combobox width reduced by the drop-down button width and margins. */
      (m_filenameCB->GetSize()).GetWidth() - 50
    )
  );
#ifdef __WXOSX__
  m_filename = filename;
#endif
}
```
Alternatively, the event handler could be deactivated (via Unbind) before calling ChangeValue and then activated (via Bind) again afterwards.

2024-07-12 21:08 UTC, nobugshere commented
@rafaelx, Thanks for the trace and tips.  I don't want to leave you hanging, so here's an update.  I've been working on my own update to this branch which, IMHO, simplifies the code and overall flow by being less reliant on event processing.  Along the way, I found a couple more issues, such as EVT_COMBOBOX being defined twice, once in the event table and again via a call to bind.  (Only the latter was being executed.)  As a result, UpdateReadOnlyCheckbox() was never called. 

I got SafeCombinationEntryDlg working well on the Mac...but broke Linux.  Eventually, I realized the new Linux problem only happened on Fedora/Xfce, not on Fedora/KDE or Ubuntu (or Mac).  I now have it working on all the platforms I've tested.  I still need to work on SafeCombinationPromptDlg.  After that, and some more testing, I'll post it for your review.

2024-07-19 16:58 UTC, rafaelx commented
@nobugshere Sorry for the late response and thanks for the improvements.
@ronys This PR is ready for the final review and merge.

2024-07-20 03:54 UTC, dskrvk commented on src/ui/wxWidgets/SafeCombinationEntryDlg.cpp
> -  if (Validate() && TransferDataFromWindow()) {
If we keep the logic this way, we can reduce the number of places EllipsizeFilePathname is called, i.e.
```
if (Validate() && TransferDataFromWindow()) {
...
}
EllipsizeFilePathname();
```

2024-07-20 03:54 UTC, dskrvk commented on src/ui/wxWidgets/SafeCombinationPromptDlg.cpp
> -  if (Validate() && TransferDataFromWindow()) {
Wanted to make the same comment as in `SafeCombinationEntry`, except that here there's no call to `EllipsizeFilePathname()` in the `!TransferDataFromWindow()` case - is that intentional?

2024-07-22 00:00 UTC, dskrvk commented
Seems like there are many places where we have to call Ellipsize, and it may be hard to avoid regressions as the code evolves (many mutually-interacting conditions to keep track of, no tests). Would it perhaps be easier to make "ellipsized" the default state and only expand the text in select circumstances where this is needed?

2024-07-24 12:41 UTC, merged