Correct generation of version number in OS X
pwsafe/pwsafe pull request #728
Opened 2021-03-14 12:28 UTC by KaiZin2018

Derive version.h from version.wx also in Mac OS build with Xcode.
Generate the name of DMG-packet in Mac OS from version.wx.

This patch will be the last to close issue #605.

2021-03-15 19:42 UTC, ronys requested changes

2021-03-15 19:42 UTC, ronys commented on Makefile.macos
> +ifdef VER_REF
Typo - should be VER_REV

2021-03-15 20:55 UTC, KaiZin2018 commented on Makefile.macos
> +ifdef VER_REF
Thank you for the correction.

2021-03-16 19:29 UTC, ronys approved these changes

2021-03-16 19:29 UTC, merged

2021-03-16 19:49 UTC, ronys commented
Mac build is broken:
   /bin/sh -c /Users/runner/Library/Developer/Xcode/DerivedData/pwsafe-xcode6-botpwyrcakxdikczrovdtjytfhdg/Build/Intermediates.noindex/pwsafe-xcode6.build/Release/pwsafe.build/Script-E6CFEEF711EA3E2F001402D8.sh
Usage: Misc/mkversion.pl MAJOR=x MINOR=y [REV=z] [SPECIAL=w] template outfile
make: *** [src/ui/wxWidgets/version.h] Error 1
Command PhaseScriptExecution failed with a nonzero exit code

2021-03-16 21:38 UTC, KaiZin2018 commented
Pull rauest #730 will fix.

2021-03-16 21:38 UTC, KaiZin2018 commented
Pull request...

2021-03-16 21:58 UTC, KaiZin2018 commented
Sorry, it look like, that I'm also blocked to create a pull request from my last two commit. I even don't know how to perform this.

Please adapt Makefile.macos starting from line 39
39 39 src/ui/wxWidgets/version.h: version.wx Misc/mkversion.pl src/ui/wxWidgets/version.in
40 40 ifdef VER_REV
41       -	@Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) REV=$(VER_REV) \
42      -
43      -                                        SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
     41 +	@Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) REV=$(VER_REV) SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
44 42 else
45      -	@Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) \
46      -                                        SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
47      -
     43 +	@Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
48 44 endif

The adaptation of README.MAC.DEVELOPERS.md is not so important and can be done later.

2021-03-16 21:59 UTC, KaiZin2018 commented
Looks like that I cannot format well, I should use the preview

2021-03-16 22:01 UTC, KaiZin2018 commented
39 39 src/ui/wxWidgets/version.h: version.wx Misc/mkversion.pl src/ui/wxWidgets/version.in
40 40 ifdef VER_REV
41 ...- @Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) REV=$(VER_REV) 
42 ...-
43 ...- SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
... 41 + @Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) REV=$(VER_REV) SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
44 42 else
45 ...- @Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) 
46 ...- SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
47 ...-
... 43 + @Misc/mkversion.pl MAJOR=$(VER_MAJOR) MINOR=$(VER_MINOR) SPECIAL=$(VER_SPECIAL) src/ui/wxWidgets/version.in $@
48 44 endif

Line 43 of new version is located at one line.