EXE/DLL Description Copyright Symbol Corruption
pwsafe/pwsafe pull request #916
Opened 2023-01-21 15:21 UTC by henricj

The RC files have `#pragma code_page(1252)` which forces `rc.exe` to interpret the files as Windows-1252 code page when parsing them.  Modern text editors tend to save files in UTF-8, so this makes keeping the version string copyright symbol from degenerating into mojibake difficult.  These commits switch the RC files to declare the UTF-8 code page (65001) and fixes the current copyright symbol corruption.  Round-tripping through VS2022 was done and the code page directive did survive.

Microsoft's Raymond Chen has a blog post about this problem: [_The Resource Compiler defaults to CP_ACP, even in the face of subtle hints that the file is UTF-8_](https://devblogs.microsoft.com/oldnewthing/20190607-00/?p=102569)

Note that the encoding for the strings inside the resulting binaries was already Unicode as can be seen from the "1200" in the "[VarFileInfo](https://learn.microsoft.com/en-us/windows/win32/menurc/varfileinfo-block)":
```
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x409, 1200
    END
```

This PR is marked "draft" since it is on top of PR #915.

2023-01-25 19:06 UTC, ronys requested changes
The value of VER_MINOR is version.mfc appears correctly in the exe properties, but in the opening window and Help->About it's not handled correctly
![image](https://user-images.githubusercontent.com/781072/214659354-6e7c5e28-c72e-4f66-b682-877612b4ebb1.png)
![image](https://user-images.githubusercontent.com/781072/214659676-7dfc0810-3751-4bd5-8100-64ed4d23f9cf.png)

2023-01-25 20:31 UTC, henricj commented
> The value of VER_MINOR is version.mfc appears correctly in the exe properties, but in the opening window and Help->About it's not handled correctly.

I added the version major/minor/patch directly to `version.h` so that the PWSversion ctor can just use them instead of playing string parsing games.  Even the "modified" flag could be handled similarly.

One other thought: The `version.h` file is only updated at configuration time.  It is usually safer to update it at build time so that if something other than a build-system file is updated, the new build will get an updated `version.h` file.  It can cause release process issues since if a file is modified after the configuration but before the build, then the release build will produce a binary with the modified flag.  This is probably an, "after a new release, not just before," change.

2023-01-28 14:19 UTC, ronys approved these changes
Fixed "0.0" problem + simplified code.

2023-01-28 14:30 UTC, ronys commented
Agh - looks like I missed commit [eb8dbd4](https://github.com/pwsafe/pwsafe/pull/916/commits/eb8dbd47d298823b338f7de94bf327baa624d5a2) and duplicated it myself!

2023-01-28 14:30 UTC, closed without merging

2023-01-28 17:26 UTC, henricj commented
> Agh - looks like I missed commit [eb8dbd4](https://github.com/pwsafe/pwsafe/pull/916/commits/eb8dbd47d298823b338f7de94bf327baa624d5a2) and duplicated it myself!

The merge collided with the same branch for me locally, on what is now #921.  Most of the difference plus some other changes I was working are there.